### PR TITLE
Acceptance tesintg

### PR DESCRIPTION
**Pull request by paneq**
What do you think ?

### CODE REVIEW

**Comment by paneq** [comment]
Any idea why this is failing: http://travis-ci.org/#!/perplexes/m2r ?

**Comment by mostlyobvious** [comment]
The reason is:
- travis has no cache so bundler always installs newest permitted gem versions
- minitest was lately released (3.3.0)
- mocha didn't [catch up](https://github.com/freerange/mocha/blob/v0.12.1/lib/mocha/integration/mini_test.rb#L53)

See also: https://github.com/seattlerb/minitest/issues/151

**Comment by mostlyobvious** [comment]
When #39 is done, we can merge it.

**Comment by mostlyobvious** [comment]
Does it work for you now @paneq ?

**Comment by paneq** [comment]
`test:acceptance` works fine for me however I see that unit tests are randomly failing:

```
(vm:sandbox) [rupert] 17:06 <1.9.3p194> ~/develop/m2r (acceptance) > bundle exec rake test:unit
Run options: --seed 55572

# Running tests:

..E.................

Finished tests in 0.055858s, 358.0486 tests/s, 662.3899 assertions/s.

  1) Failure:
test_receive_message(M2R::ConnectionTest) [/home/rupert/develop/m2r/test/unit/connection_test.rb:12]:
Could not bind push socket in tests.
Expected: 0
  Actual: -1

  2) Error:
test_receive_message(M2R::ConnectionTest):
NoMethodError: undefined method `close' for nil:NilClass
    /home/rupert/develop/m2r/test/unit/connection_test.rb:27:in `teardown'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/mocha-0.12.1/lib/mocha/integration/mini_test/version_2112_to_320.rb:44:in `block in run'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/mocha-0.12.1/lib/mocha/integration/mini_test/version_2112_to_320.rb:42:in `each'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/mocha-0.12.1/lib/mocha/integration/mini_test/version_2112_to_320.rb:42:in `run'

20 tests, 37 assertions, 1 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [/home/rupert/binary/ruby-1.9.3-p194/bin/ru...]

Tasks: TOP => test:unit
(See full trace by running task with --trace)

```

**Comment by paneq** [comment]
Anyway it is a separate issue and I think we can merge this branch

**Comment by mostlyobvious** [comment]
I'll fix #39 tomorrow and merge it, thanks!

**Comment by paneq** [comment]
Cool

**Comment by paneq** [comment]
When I run 4 programs to burn all my CPUs I sometimes get:

```

.E

Finished tests in 9.699446s, 0.2062 tests/s, 0.0000 assertions/s.

  1) Error:
test_handler_example(M2R::ExamplesTest):
RuntimeError: Received the following error for a GET request to http://localhost:6767/rack: 'connection refused: localhost:6767'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-mechanize-0.3.0/lib/capybara/mechanize/browser.rb:177:in `rescue in process_remote_request'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-mechanize-0.3.0/lib/capybara/mechanize/browser.rb:171:in `process_remote_request'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-mechanize-0.3.0/lib/capybara/mechanize/browser.rb:56:in `process_without_redirect'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-mechanize-0.3.0/lib/capybara/mechanize/browser.rb:96:in `get'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-mechanize-0.3.0/lib/capybara/mechanize/browser.rb:48:in `process'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-1.1.2/lib/capybara/rack_test/browser.rb:21:in `visit'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-1.1.2/lib/capybara/rack_test/driver.rb:32:in `visit'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-1.1.2/lib/capybara/session.rb:157:in `visit'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/capybara-1.1.2/lib/capybara/dsl.rb:161:in `visit'
    /home/rupert/develop/m2r/test/acceptance/examples_test.rb:15:in `test_handler_example'
    /home/rupert/binary/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/mocha-0.12.1/lib/mocha/integration/mini_test/version_2112_to_320.rb:32:in `run'

2 tests, 0 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [/home/rupert/binary/ruby-1.9.3-p194/bin/ru...]

Tasks: TOP => test:acceptance
(See full trace by running task with --trace)
(vm:sandbox) [rupert] 22:35 <1.9.3p194> ~/develop/m2r (acceptance) > bundle exec rake test:acceptance
Run options: --seed 2273
```

However now I could not reproduce the error in unit tests :)

**Pull request merged**
